account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = []

urlpatterns += [
    path('revenues/', views.RevenueIndex.as_view(), name='revenues'),
    path('revenue/payment/<int:pk>/', views.add_revenue_to_job, name='add_revenue_to_job'),

]

urlpatterns += [
    # path('expendituretypes/', views.ExpenditureIndex.as_view(), name='expenditure_types'),
    path('expendituretype/new/', views.NewExpenditureType.as_view(), name='new_expenditure_type'),
]

urlpatterns += [
    path('expenditures/', views.ExpenditureIndex.as_view(), name='expenditures'),
    path('expenditures/new', views.NewExpenditure.as_view(), name='new_expenditure'),
    path('expenditures/expense/<int:pk>/', views.add_expenditure_to_job, name='add_expenditure_to_job'),
]

urlpatterns += [
    path('accounting/', views.accounting, name='accounting')
]

personnel/urls.py
"""Urls"""

from django.urls import reverse_lazy, path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'personnel'

urlpatterns = []

urlpatterns += [
    path('index/', views.PersonnelIndex.as_view(), name='index'),
]

urlpatterns += [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('logout-then-login/', auth_views.logout_then_login, name='logout_then_login'),

    path('password_change/', auth_views.PasswordChangeView.as_view(
        success_url=reverse_lazy('personnel:password_change_done')), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(
        success_url=reverse_lazy('personnel:password_reset_done')), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        success_url=reverse_lazy('personnel:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = []

urlpatterns += [
    path('customers/index/', views.CustomerIndex.as_view(), name='customer_index'),
    path('customers/new/', views.NewCustomer.as_view(), name='customer_new'),
    path('customers/<int:pk>/', views.customer_details, name='customer_details'),
    path('customers/edit/<int:pk>/', views.EditCustomer.as_view(), name='edit_customer'),
]

urlpatterns += [
    path('jobs/index/', views.JobIndex.as_view(), name='job_index'),
    path('jobs/new/', views.NewJob.as_view(), name='job_new'),
    path('jobs/edit/<int:pk>/', views.EditJob.as_view(), name='job_edit'),
    path('jobs/<int:pk>/', views.JobDetail.as_view(), name='job_detail'),
    path('jobs/update-status/<int:pk>/', views.UpdateJobStatus.as_view(), name='job_update_status'),
    path('jobs/mark-accepted/<int:pk>', views.mark_accepted, name='job_mark_accepted'),
    path('jobs-filter', views.JobFilterView.as_view(), name='job_filter'),
]

templates/home.html
{% extends "viani_base.html" %}

{% block content %}

<div class="home">
    <h3><a href="/shop/jobs/index">Jobs</a></h3>
    <h3><a href="/shop/customers/index">Customers</a></h3>
    <h3><a href="/account/revenues">Revenues</a></h3>
    <h3><a href="/account/expenditures">Expenditures</a></h3>
</div>
{% endblock content %}

templates/messages.html
{% block messages %}
{% if messages %}
    {% for message in messages %}
      <div class="row alert {{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
      </div>
    {% endfor %}
{% endif %}
{% endblock messages %}

templates/navigation_right.html
{% load thumbnail %}
{% load static %}

<ul class="navbar-nav ml-auto">
    {% if request.user.is_authenticated %}
    <li class="nav-item dropdown">
        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Shop <span class="caret"></span></a>
        <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'shop:job_index' %}">Jobs</a></li>
            <li><a class="dropdown-item" href="{% url 'shop:customer_index' %}">Customers</a></li>
        </ul>
    </li>

    <li class="nav-item dropdown">
        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
        <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'account:revenues' %}">Revenues</a></li>
            <li><a class="dropdown-item" href="{% url 'account:expenditures' %}">Expenditures</a></li>
            <li><a class="dropdown-item" href="{% url 'account:accounting' %}">Summary</a></li>
        </ul>
    </li>

    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><i class="fas fa-plus"></i></a>
        <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'shop:job_new' %}">Job</a>
            <a class="dropdown-item" href="{% url 'shop:customer_new' %}">Customer</a>
            <a class="dropdown-item" href="{% url 'account:new_expenditure' %}">Expenditure</a>
            <div class="divider"></div>
            <a class="dropdown-item" href="{% url 'account:new_expenditure_type' %}">Expenditure type</a>
        </div>
    </li>

    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-circle"></i></a>
        <div class="dropdown-menu">

            <a class="dropdown-item" href="#">Edit profile</a>
            {% if request.user.personnel.avatar %}
                <a class="dropdown-item" href="#">Change avatar</a>
            {% else %}
                <a class="dropdown-item" href="#">Add avatar</a>
            {% endif %}

            <a class="dropdown-item" href="{% url 'personnel:password_reset' %}">Reset password</a>
            <a class="dropdown-item" href="{% url 'personnel:password_change' %}">Change password</a>
            {% if user.is_admin %}
            <a class="dropdown-item text-success" href="/admin/">Admin</a>
            {% endif %}
            <a class="dropdown-item" href="{% url 'personnel:logout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a>
        </div>
    </li>


    {% else %}
        <a class="nav-link" href="{% url 'personnel:login' %}">Login <i class="fas fa-sign-in-alt"></i></a>
    {% endif %}
</ul>

templates/pure_pagination.html
{% load i18n %}
{% block pure_pagination %}

<div class="container">
    <div class="row">
        <div class="pagination ml-auto mr-auto bg-primary">
            {% if page_obj.has_previous %}
                <a href="?{{ page_obj.previous_page_number.querystring }}" class="prev">&lsaquo;&lsaquo; {% trans "prev" %}</a>
            {% else %}
                <span class="disabled prev">&lsaquo;&lsaquo; {% trans "prev" %}</span>
            {% endif %}
            {% for page in page_obj.pages %}
                {% if page %}
                    {% ifequal page page_obj.number %}
                        <span class="current page">{{ page }}</span>
                    {% else %}
                        <a href="?{{ page.querystring }}" class="page">{{ page }}</a>
                    {% endifequal %}
                {% else %}
                    ...
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <a href="?{{ page_obj.next_page_number.querystring }}" class="next">{% trans "next" %} &rsaquo;&rsaquo;</a>
            {% else %}
                <span class="disabled next">{% trans "next" %} &rsaquo;&rsaquo;</span>
            {% endif %}
        </div>
    </div>
</div>

{% endblock pure_pagination %}

templates/viani_base.html
<!DOCTYPE html>

<html>
    <head>
		{% load staticfiles %}
		{% load static %}
        {% load thumbnail %}

        <title>{% block title %}Home{% endblock title %} - Viani</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Viani. Fashion design is our passion">
        <meta name="keywords" content="viani, fasion designers, clothes, events">
        <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->
        <link rel="stylesheet" href="https://bootswatch.com/4/slate/bootstrap.min.css"crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

        <link rel="stylesheet" href="{% static 'css/viani.css' %}">

		<!--Django add another, for view popup. These two below lines must follow one another in the same order.-->
		<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
        {{ form.media }}
    </head>

    <body class="bg-secondary">
        {% block body %}

        <div class="page_wrapper">
            <div class="page_top">
                {% block navigation %}

                <header>
                    <nav class="navbar navbar-expand-md navbar-dark bg-primary" role="navigation">
                        <div class="container">
                            <a class="navbar_brand" href="/">Viani</a>
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                                    <span class="sr-only">Toggle navigation</span>
                                <span class="navbar-toggler-icon"></span>
                            </button>

                            <div class="collapse navbar-collapse navcontent" id="navbarColor02">
                                {% include "navigation_right.html" %}
                            </div>
                        </div>
                    </nav>
                </header>

                {% endblock navigation %}

                <div class="body_container">
                    {% include 'messages.html' %}
                    {% block content %}
                    {% endblock content %}
                </div>

                {% if is_paginated %}
                    {% include "pure_pagination.html" %}
                {% endif %}
            </div>

            <footer>
                <div class="footer_text">
                    <p>Viani</p>
                    <p>Contact us: +2349036650603 | orjichidi95@gmail.com</p>
                    <p><a class="" href="https://www.instagram.com/vianifashion/" target="_blank">Instagram <i class="fas fa-external-link-alt"></i></a> | <a class="" href="#">Twitter</a></p>
                </div>
            </footer>
        </div>

        {% endblock body %}
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js" async></script>

        {% block page_js %}{% endblock page_js %}

        <script>
            $(".dropdown-toggle").on("mouseenter", function () {
                // make sure it is not shown:
                if (!$(this).parent().hasClass("show")) {
                    $(this).click();
                }
            });

            $(".btn-group, .dropdown").on("mouseleave", function () {
                // make sure it is shown:
                if ($(this).hasClass("show")){
                    $(this).children('.dropdown-toggle').first().click();
                }
            });
        </script>
    </body>
</html>