account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = []

urlpatterns += [
    path('revenues/', views.RevenueIndex.as_view(), name='revenues'),
    path('revenue/payment/<int:pk>/', views.add_revenue_to_job, name='add_revenue_to_job'),

]

urlpatterns += [
    # path('expendituretypes/', views.ExpenditureIndex.as_view(), name='expenditure_types'),
    path('expendituretype/new/', views.NewExpenditureType.as_view(), name='new_expenditure_type'),
]

urlpatterns += [
    path('expenditures/', views.ExpenditureIndex.as_view(), name='expenditures'),
    path('expenditures/new', views.NewExpenditure.as_view(), name='new_expenditure'),
    path('expenditures/expense/<int:pk>/', views.add_expenditure_to_job, name='add_expenditure_to_job'),
]

urlpatterns += [
    path('accounting/', views.accounting, name='accounting')
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = []

urlpatterns += [
    path('customers/index/', views.CustomerIndex.as_view(), name='customer_index'),
    path('customers/new/', views.NewCustomer.as_view(), name='customer_new'),
    path('customers/<int:pk>/', views.customer_details, name='customer_details'),
    path('customers/edit/<int:pk>/', views.EditCustomer.as_view(), name='edit_customer'),
]

urlpatterns += [
    path('jobs/index/', views.JobIndex.as_view(), name='job_index'),
    path('jobs/new/', views.NewJob.as_view(), name='job_new'),
    path('jobs/edit/<int:pk>/', views.EditJob.as_view(), name='job_edit'),
    path('jobs/<int:pk>/', views.JobDetail.as_view(), name='job_detail'),
    path('jobs/update-status/<int:pk>/', views.UpdateJobStatus.as_view(), name='job_update_status'),
    path('jobs/mark-accepted/<int:pk>', views.mark_accepted, name='job_mark_accepted'),
    path('jobs-filter', views.JobFilterView.as_view(), name='job_filter'),
]

account/models.py
from decimal import Decimal

from django.db import models
from django.shortcuts import reverse
from django.utils.timezone import now

from shop.models import Job
from personnel.models import Personnel

from .utils.models import TimeStampedModel


class Revenue(TimeStampedModel):
    date = models.DateField(default=now)
    personnel = models.ForeignKey(Personnel, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    locked = models.BooleanField(default=False)
    locker = models.CharField(max_length=25)
    job = models.ForeignKey(
        Job, on_delete=models.CASCADE, null=True, blank=True)
    notes = models.CharField(max_length=250, blank=True)

    class Meta:
        ordering = ('locked', '-date')

    def __str__(self):
        return f'Rev: {self.amount}'

    def get_absolute_url(self):
        return reverse('bet9ja:revenues')

    def get_object_url(self):
        return reverse('bet9ja:revenue_detail', kwargs={'pk': self.id})


class ExpenditureType(TimeStampedModel):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=250, blank=True)

    class Meta:
        ordering = ('name', '-created')

    def __str__(self):
        return f'Etype: {self.name.title()}'

    def get_absolute_url(self):
        return reverse('account:expenditures')


class Expenditure(TimeStampedModel):
    date = models.DateField(default=now)
    item = models.CharField(max_length=50, null=True, blank=True)
    job = models.ForeignKey(
        Job, on_delete=models.CASCADE, null=True, blank=True)
    amount = models.DecimalField(
        max_digits=10, decimal_places=2, default=Decimal('0.00'))

    locked = models.BooleanField(default=False)
    locker = models.CharField(max_length=25)
    personnel = models.ForeignKey(
        Personnel, null=True, on_delete=models.SET_NULL)
    category = models.ForeignKey(
        ExpenditureType, null=True, on_delete=models.SET_NULL)
    notes = models.CharField(max_length=250, blank=True)

    class Meta:
        ordering = ('locked', '-date')

    def __str__(self):
        return f'Exp: {self.item}-{self.amount}'

    def get_absolute_url(self):
        return reverse('account:expenditures')

    def get_object_url(self):
        return reverse('account:expenditure_detail', kwargs={'pk': self.id})


class MonthCheck(TimeStampedModel):
    year = models.IntegerField()
    month = models.IntegerField()
    value = models.DecimalField(max_digits=10, decimal_places=2)
    personnel = models.ForeignKey(
        Personnel, null=True, on_delete=models.SET_NULL, related_name='balance_creator')

    class Meta:
        ordering = ('-year', '-month')

shop/utils/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from .fields import AutoCreatedField, AutoLastModifiedField

class TimeStampedModel(models.Model):
    """
    An abstract base class model that provides self-updating
    ``created`` and ``modified`` fields.
    """
    created = AutoCreatedField(_('created'))
    modified = AutoLastModifiedField(_('modified'))

    class Meta:
        abstract = True

shop/views.py
import datetime
import operator
from functools import reduce

from django.views import generic
from django.db.models import Q, Sum
from django.contrib import messages
from django.shortcuts import render, redirect, reverse
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin

from django_addanother.views import CreatePopupMixin
from pure_pagination.mixins import PaginationMixin

from account.models import Revenue, Expenditure

from .utils import context_messages as cm

from .models import Customer, Job
from .forms import (
    NewCustomerForm, EditCustomerForm, NewJobForm, EditJobForm,
    UpdateJobStatusForm, JobFilterForm
)

from v_rules.PermissionBackend import vianirules


class CustomerIndex(LoginRequiredMixin, PaginationMixin,  generic.ListView):
    model = Customer
    template_name = 'shop/customer_index.html'
    context_object_name = 'customers'
    paginate_by = 100

    def get_queryset(self):
        return super().get_queryset()


class NewCustomer(CreatePopupMixin, LoginRequiredMixin, SuccessMessageMixin, generic.CreateView):
    model = Customer
    template_name = 'shop/customer_new.html'
    form_class = NewCustomerForm
    success_message = 'Customer added successfully !'

    def dispatch(self, request, *args, **kwargs):
        user = self.request.user
        rule_to_check = 'create_customer'
        if vianirules.has_permission(rule_to_check, request):
            return super().dispatch(request, *args, **kwargs)
        messages.error(self.request, cm.OPERATION_FAILED)
        return redirect('/')


class EditCustomer(LoginRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    model = Customer
    template_name = 'shop/customer_edit.html'
    form_class = EditCustomerForm
    success_message = 'Customer updated successfully !'

    def get_success_url(self, **kwargs):
        return reverse('shop:customer_details', kwargs={'pk': self.kwargs['pk']})

    def dispatch(self, request, *args, **kwargs):
        user = self.request.user
        rule_to_check = 'edit_customer'

        if vianirules.has_permission(rule_to_check, request):
            return super().dispatch(request, *args, **kwargs)
        messages.error(self.request, cm.OPERATION_FAILED)
        return redirect('/')


def customer_details(request, pk):
    template = 'shop/customer_details.html'
    context = {}
    context['customer'] = Customer.objects.get(pk=pk)
    context['customer_jobs'] = Job.objects.filter(customer__pk=pk)
    return render(request, template, context)


class JobIndex(LoginRequiredMixin, PaginationMixin, generic.ListView):
    model = Job
    template_name = 'shop/job_index.html'
    context_object_name = 'jobs'
    paginate_by = 100

    def dispatch(self, request, *args, **kwargs):
        rule_to_check = 'view_jobs_index'
        if vianirules.has_permission(rule_to_check, self.request):
            return super().dispatch(request, *args, **kwargs)
        messages.error(self.request, cm.OPERATION_FAILED)
        return redirect('/')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        completed_job_count = Job.objects.filter(status=4).count()
        total_job_count = Job.objects.count()

        context['completed_job_count'] = completed_job_count
        context['total_job_count'] = total_job_count
        try:
            completion_rate = (completed_job_count / total_job_count) * 100
        except ZeroDivisionError:
            completion_rate = 1
        context['completion_rate'] = round(completion_rate, 2)
        context['job_filter_form'] = JobFilterForm()
        context['filter_view'] = False

        overall_value = Job.objects.aggregate(total=Sum('value'))['total']
        context['overall_value'] = overall_value

        overall_discount = Job.objects.aggregate(
            total=Sum('discount'))['total']
        context['overall_discount'] = overall_discount

        overall_payment = Revenue.objects.aggregate(
            total=Sum('amount'))['total']
        context['overall_payment'] = overall_payment

        overall_job_expenditure = Expenditure.objects.filter(category__name__in=[
                                                             'materials', 'external job']).aggregate(total=Sum('amount'))['total']
        context['overall_job_expenditure'] = overall_job_expenditure

        overall_profit = 0
        overall_profit += overall_payment if overall_payment else 0
        overall_profit -= overall_job_expenditure if overall_job_expenditure else 0
        context['overall_profit'] = overall_profit
        return context


class NewJob(LoginRequiredMixin, SuccessMessageMixin, generic.CreateView):
    model = Job
    form_class = NewJobForm
    template_name = 'shop/job_new.html'

    def dispatch(self, request, *args, **kwargs):
        user = self.request.user
        rule_to_check = 'create_job'
        if vianirules.has_permission(rule_to_check, request):
            return super().dispatch(request, *args, **kwargs)
        messages.error(self.request, cm.OPERATION_FAILED)
        return redirect('/')


class EditJob(LoginRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    model = Job
    form_class = EditJobForm
    template_name = 'shop/job_edit.html'

    def get_success_url(self, **kwargs):
        return reverse('shop:job_detail', kwargs={'pk': self.kwargs['pk']})

    # def dispatch(self, request, *args, **kwargs):
    #     user = self.request.user
    #     rule_to_check = 'edit_job'
    #     if vianirules.has_permission(rule_to_check, request):
    #         return super().dispatch(request, *args, **kwargs)
    #     messages.error(self.request, cm.OPERATION_FAILED)
    #     return redirect(reverse('shop:job_detail', kwargs={'pk': self.kwargs['pk']}))


def mark_accepted(request, pk):
    user = request.user

    rule_to_check = 'mark_accepted'
    if vianirules.has_permission(rule_to_check, request):
        job = Job.objects.get(pk=pk)
        job.status = 4
        job.save()
        return redirect(reverse('shop:job_detail', kwargs={'pk': pk}))
    messages.error(request, cm.OPERATION_FAILED)
    return redirect(reverse('shop:job_detail', kwargs={'pk': pk}))


class JobDetail(LoginRequiredMixin, generic.DetailView):
    model = Job
    template_name = 'shop/job_detail.html'
    context_object_name = 'job'


class UpdateJobStatus(LoginRequiredMixin, SuccessMessageMixin,  generic.UpdateView):
    model = Job
    template_name = 'shop/job_update_status.html'
    form_class = UpdateJobStatusForm
    success_message = "Job status updated successfully."

    def get_success_url(self, **kwargs):
        return reverse('shop:job_detail', kwargs={'pk': self.kwargs['pk']})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['job'] = Job.objects.get(pk=self.kwargs['pk'])
        return context


class JobFilterView(LoginRequiredMixin, PaginationMixin, generic.ListView):
    model = Job
    template_name = 'shop/job_index.html'
    context_object_name = "jobs"
    paginate_by = 100

    def get_context_data(self, **kwargs):
        context = super(JobFilterView, self).get_context_data(**kwargs)
        context['job_filter_form'] = JobFilterForm()
        context['filter_view'] = True
        return context

    def get_queryset(self):
        if self.request.method == 'GET':
            form = JobFilterForm(self.request.GET)

            if form.is_valid():
                form = form.cleaned_data

                customer = form['customer']
                phase = form['phase']
                start_date = form['start_date']
                completed = form['completed']
                to_date = form['to_date']

                # build queries
                phases = {1: 'Started', 2: "Finished",
                          3: 'Delivered', 4: 'Accepted'}
                queries = []
                msg = []
                if customer:
                    queries.append(Q(customer=customer))
                    msg.append(f'{customer}')
                if phase:
                    queries.append(Q(status=phase))
                    msg.append(f'{phases[int(phase)]} jobs')

                if completed:
                    if not to_date:
                        to_date = start_date + datetime.timedelta(days=30)
                    queries.append(Q(start_date__range=[start_date, to_date]))
                    msg.append(f'Completed between {start_date} and {to_date}')

                if start_date:
                    if not to_date:
                        to_date = start_date + datetime.timedelta(days=30)
                    queries.append(Q(start_date__range=[start_date, to_date]))
                    msg.append(f'Started between {start_date} and {to_date}')

                # combine queries
                try:
                    query = reduce(operator.and_, queries)
                    query_str = " AND ".join(msg)
                except TypeError:
                    query = []
                    query_str = ""
                    messages.success(
                        self.request, "You did not make any selection")
                    return Job.objects.all().order_by('status', 'customer', '-start_date')

                # execute query
                messages.success(
                    self.request, "Search results for {}".format(query_str))
                return Job.objects.filter(query).order_by('status', 'customer', '-start_date')

shop/templates/shop/accounting.html
{% extends "viani_base.html" %}
{% block title %}Accounting{% endblock %}

{% block content %}

<h1>Accounting</h1>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Shop</a></li>
        <li class="breadcrumb-item active">Accounting</li>
    </ol>
</nav>

<div class="row">
    <div class="col-sm-6">
        <h2>Accounts summary</h2>
        <div class="dropdown-divider"></div>
        <h3>Job value: <span class="text-danger">{{ total_job_value }}</span></h3>
        <h3>Income: <span class="text-danger">{{ total_payments }}</span></h3>
        <h3>Expenses: <span class="">{{ total_expenses }}</span></h3>
        <h3>Discounts: <span class="">{{ total_discounts }}</span></h3>
        <h3>Gross Profit: <span class="text-secondary">{{ gross_profit }}</span></h3>
        <h3>Net profit: <span class="text-success">{{ net_profit }}</span></h3>
    </div>

    <div class="col-sm-6">
        <h2>Account statements</h2>
        <div class="dropdown-divider"></div>
    </div>
</div>


{% endblock content %}

shop/templates/shop/cashflow_new.html
{% extends "viani_base.html" %}
{% block title %}New cashflow{% endblock %}

{% block content %}

<h1>New cashflow</h1>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Shop</a></li>
        <li class="breadcrumb-item active">New cashflow</li>
    </ol>
</nav>

<div class="form_container">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <p>{{ form.as_p }}</p>

        <button class="btn btn-primary btn-md" type="submit" value="Save">Save</button>
    </form>
</div>

{% endblock content %}

shop/templates/shop/cashflowtype_new.html
{% extends "viani_base.html" %}
{% block title %}New cashflow type{% endblock %}

{% block content %}

<h1>New cashflow type</h1>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Shop</a></li>
        <li class="breadcrumb-item active">New cashflow type</li>
    </ol>
</nav>

<div class="form_container">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <p>{{ form.as_p }}</p>

        <button class="btn btn-primary btn-md" type="submit" value="Save">Save</button>
    </form>
</div>

{% endblock content %}

shop/templates/shop/customer_details.html
{% extends "viani_base.html" %}
{% block title %}{{ customer }}{% endblock title %}
{% block content %}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Shop</a></li>
        <li class="breadcrumb-item"><a href="/shop/customers/index/">Customers</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ customer }}</li>
    </ol>
</nav>

<div class="row">
    <div class="col-sm-12 job_actions_grid">
        <div class="job_actions">
            <a href="{% url 'shop:edit_customer' customer.pk %}"><button class="btn btn-md btn-success">Edit</button></a>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="card viani_card">
            <div class="customer">
                <h4>{{ customer }}</h4>
            </div>
            <hr>
            <div class="details">
                <p>{{ customer.sex.title }}</p>
                <p>{% if customer.phone %}{{ customer.phone }}{% else %}Phone{% endif %}</p>
                <p>{{ customer.address }}</p>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="card viani_card">
            <h4>Jobs</h4>
            <hr>

            {% for job in customer_jobs%}
            <h5>{{ forloop.counter }}.
                    <a href="{% url 'shop:job_detail' job.pk %}">
                        {{ job }} - {{ job.value }}
                        {% if job.status == 4 %}<i class="fas fa-check-circle text-success"></i>{% endif %}
                    </a>
                    </h5>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}

shop/templates/shop/customer_edit.html
{% extends "viani_base.html" %}
{% block title %}Edit customer{% endblock %}
{% block content %}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Shop</a></li>
        <li class="breadcrumb-item"><a href="{% url 'shop:customer_index' %}">Customers</a></li>
        <li class="breadcrumb-item active">Edit customer</li>
    </ol>
</nav>

<div class="form_container">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <p>{{ form.as_p }}</p>

        <button class="btn btn-primary btn-md" type="submit" value="Save">Save</button>
    </form>
</div>

{% endblock content %}

shop/templates/shop/customer_index.html
{% extends "viani_base.html" %}
{% block title %}Customers{% endblock title %}
{% block content %}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Shop</a></li>
    <li class="breadcrumb-item active" aria-current="page">Customers</li>
  </ol>
</nav>

<div class="table-responsive">
  <table>
    <thead>
      <tr class="bg-dark">
        <th>S/N</th>
        <th>Name</th>
        <th>Phone</th>
        <th>Address</th>
        <th>Sex</th>
        <th>Jobs</th>
        <th>Action</th>
      </tr>
    </thead>

    {% if customers %}
    <tbody>
      {% for customer in customers %}
      <tr>
        <td>{{ forloop.counter }}</td>
        <td><a href="{% url 'shop:customer_details' customer.pk %}">{{ customer.first_name.title }}
            {{ customer.last_name.title }}</a></td>
        <td>{{ customer.phone }}</td>
        <td>{{ customer.address.title }}</td>
        <td>{{ customer.sex.title }}</td>
        <td>{{ customer.job_count }}</td>
        <td><a href="{% url 'shop:edit_customer' customer.pk %}"><i class="fas fa-edit"></i></a></td>
      </tr>
      {% endfor %}
    </tbody>
    {% else %}
    <p>No customers to show</p>
    {% endif %}
  </table>
</div>

{% endblock content %}

shop/templates/shop/customer_new.html
{% extends "viani_base.html" %}
{% block title %}New customer{% endblock %}

{% block content %}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Shop</a></li>
        <li class="breadcrumb-item"><a href="{% url 'shop:customer_index' %}">Customers</a></li>
        <li class="breadcrumb-item active">New customer</li>
    </ol>
</nav>

<div class="form_container">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <p>{{ form.as_p }}</p>

        <button class="btn btn-primary btn-md" type="submit" value="Save">Save</button>
    </form>
</div>

{% endblock content %}

shop/templates/shop/job_detail.html
{% extends "viani_base.html" %}
{% block title %}{{ job }}{% endblock %}
{% load shop_tags_and_filters %}
{% block content %}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Shop</a></li>
        <li class="breadcrumb-item"><a href="/shop/jobs/index/">Jobs</a></li>
        <li class="breadcrumb-item active">{{ job }}</li>
    </ol>
</nav>

<div class="row">
    <div class="col-sm-12 job_actions_grid">
        <div class="job_actions">
            <a href="{% url 'account:add_revenue_to_job' job.pk %}"><button class="btn btn-md btn-success">Add payment</button></a>
            <a href="{% url 'account:add_expenditure_to_job' job.pk %}"><button class="btn btn-md btn-danger">Add expense</button></a>
            <a href="{% url 'shop:job_update_status' job.pk %}"><button class="btn btn-md btn-info">Update status</button></a>
            <a href="{% url 'shop:job_edit' job.pk %}"><button class="btn btn-md btn-primary">Edit</button></a>
            <a href="{% url 'shop:job_mark_accepted' job.pk %}"><button class="btn btn-md btn-success">Mark Accepted</button></a>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="card viani_card">
            <div class="description">
                <h4>{{ job.description.title }}</h4>
            </div>
            <hr>

            <div class="figures">
                <div class="container">
                    <div class="row">
                        <div class="job__status-date">
                            <div class="">
                                {{ job.status|status_text }}
                                {% if job.status == 4 %}<i class="fas fa-check-circle text-success"></i>{% endif %}
                            </div>
                            <div class="">{{ job.start_date }}</div>
                            <div class="">{{ job.completed }}</div>

                        </div>
                    </div>
                </div>
                <hr>
                <p>Value: {{ job.value }}</p>
                <p>Discount: {{ job.discount }}</p>
                <p class="text-success">Payment: {{ job.total_payment }}</p>
                <p class="text-danger">Expenses: {{ job.total_expenditure }}</p>
                <p>Net profit: {{ job.net_profit }}</p>
                <p>Description: {{ job.description }}</p>
            </div>
        </div>
    </div>

    <div class="col-md-6">

        <div class="card viani_card">
            <div class="customer">
                <h4>{{ job.customer }}</h4>
            </div>
            <hr>
            <div class="details">
                <p>{% if job.customer.phone %}{{ job.customer.phone }}{% else %}Phone{% endif %}</p>
                <p><a href="{% url 'shop:customer_details' job.customer.pk %}">Go to customer details</a></p>
            </div>
        </div>
        <div class="card viani_card">
            <h4>Payments</h4>
            <hr>
            {% for rev in job.revenue_set.all %}
            <p class="text-success">
                {{ forloop.counter }}.
                {{ rev.amount }} on {{ rev.date }}
            </p>
            {% endfor %}
        </div>
        <div class="card viani_card">
            <h4>Expenses</h4>
            <hr>
            {% for rev in job.expenditure_set.all %}
            <p class="text-danger">
                {{ forloop.counter }}.
                {{ rev.amount }} on {{ rev.date }}
            </p>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}

shop/templates/shop/job_index.html
{% extends "viani_base.html" %}
{% block title %}Jobs{% endblock title %}
{% load shop_tags_and_filters %}
{% load v_rules %}
{% block content %}


<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Shop</a></li>
        <li class="breadcrumb-item active" aria-current="page">Jobs</li>
    </ol>
</nav>

<div class="item-filter">
    <form action="{% url 'shop:job_filter' %}" method="get" enctype="multipart/form-data">
        <div class="filter_fields text-center">
            {% for field in job_filter_form %}
            <span>{{ field.label }}{{ field }}</span>
            {% endfor %}
        </div>
        <button class="btn btn-primary btn-md" type="submit" value="Continue">Continue</button>
    </form>
</div>

<div class="table-responsive">
    <table class="jobs_table">
        <thead>
            <tr class="bg-dark">
                <th>S/N</th>
                <th>Title</th>
                <th>Customer</th>
                <th>Status</th>
                <th>Value</th>
                <th>Discount</th>
                <th>Expense</th>
                <th>Payment</th>
                <th>Profit</th>
                <th>Action</th>
            </tr>
        </thead>

        {% if jobs %}
        <tbody>
            {% for job in jobs %}

            {% if job.status == 4 %}
                <tr class='job-completed'>
            {% else %}
                <tr>
            {% endif %}
                    <td>{{ forloop.counter }}</td>
                    <td><a href="{% url 'shop:job_detail' job.pk %}">{{ job.description|title }}</a></td>
                    <td>{{ job.customer }}</td>
                    <td>{{ job.status|status_text }}</td>
                    <td>{{ job.value }}</td>
                    <td>{{ job.discount }}</td>
                    <td>{{ job.expenditure_set.all|sum_amounts }}</td>
                    <td>{{ job.revenue_set.all|sum_amounts }}</td>
                    <td>{{ job|get_job_profit }}</td>
                    <td style="padding: 0;">
                        <a href="{% url 'shop:job_edit' job.pk %}"><i class="fas fa-edit"></i></a> |
                        <a href="{% url 'shop:job_edit' job.pk %}"><i class="fas fa-plus text-primary"></i></a> |
                        <a href="{% url 'shop:job_edit' job.pk %}"><i class="fas fa-minus text-danger"></i></a>
                    </td>
                </tr>
            {% endfor %}
            <tr class="summation_row bg-dark">
                <td>Page sum</td>
                <td></td>
                <td></td>
                <td></td>
                <td>{{ jobs|summ_values }}</td>
                <td>{{ jobs|summ_discounts }}</td>
                <td class="text-danger">{{ jobs|summ_total_expenses }}</td>
                <td>{{ jobs|summ_total_payments }}</strong></td>
                <td class="text-success">{{ jobs|summ_profits }}</td>
                <td></td>
            </tr>

            {% test_permission 'view_overall_sum' request as view_overall_sum %}
            {% if view_overall_sum %}
            <tr class="summation_row bg-dark">
                <td>Overall job sum</td>
                <td></td>
                <td></td>
                <td></td>
                <td>{{ overall_value }}</td>
                <td>{{ overall_discount }}</td>
                <td class="text-danger">{{ overall_job_expenditure }}</td>
                <td>{{ overall_payment }}</strong></td>
                <td class="text-success">{{ overall_profit }}</td>
                <td>{{ completed_job_count }} of {{ total_job_count }} ({{ completion_rate }}%)</td>
            </tr>
            {% endif %}

        </tbody>
        {% else %}
            <p>No jobs to show</p>
        {% endif %}
    </table>
</div>

{% endblock content %}